# Grading process


GA #1 is submitted individually. The submission notebook will be automatically validated with Papermill. The exact command is the following:

```bash
papermill <notebook-name>.ipynb <notebook-name>-run.ipynb .ipynb -p TEST True
```

Papermill will inject new cell after each cell tagged as `parameters` (see `View > Cell toolbar > Tags`). Notebook will be executed from top to bottom in a linear order. `solutions.py` contains correct implementations used to validate your solutions, and is only available to instructors and TA's.

Please, **fill `STUDENT` variable with your name**, so that we can collect the results automatically. Please, do not change `parameters` (specifically, **do not change `TEST` variable**) and `validation` cells for grader to work correctly. You can, though, use the following clauses to wrap your code outside of `solution` cells:

```python
if not TEST:
    <some code >
```

Each problem contains specific validation details. You need to fill each cell tagged `solution` with your code. Note, that solution function must be self-contained, i.e. it must not use any state from the notebook itself.

Different problems result in different number of points. All problems in the basic section give 1 point, while all problems in intermediate section give 2 points. Total number of points are then divided by maximum number of points (11 in this assignment) and multiplied by 100 to get your final grade (0-100).

You may find the following NumPy functions useful:

- reduction functions: `np.mean`, `np.std`, `np.max`,
- array creation functions: `np.zeros`, `np.arange`, `np.linspace`,
- element-wise functions: `np.sin`, `np.isfinite`, `np.clip`,
- other functions: `np.argmax`, `np.unique`, `np.column_stack`.

In [1]:
import numpy as np

In [2]:
STUDENT = "Itay Koren and Elia Yakin" # use your name here

In [3]:
ASSIGNMENT = 1
TEST = False

In [4]:
if TEST:
    import solutions
    total_grade = 0
    MAX_POINTS = 11

# Basic arrays

Problems 1, 2 and 3 cover the correct usage of `np.arange` (or `np.linspace` for that matter), basic masking and vectorized functions (like calculating `sin` of each element of an array in a vectorized manner).

### 1. Calculate $\sin(x)$ for $0\leq x < 2\pi$ with a step of $0.1$.

You need to implement a function, which calculates the required array. The exact values of $x$ are $[0, 0.1, 0.2,\ldots,6.2]$.

Result must be **1-dimensional**, and **will be tested against precomputed values**.

Note, that `numpy` provides [constants](https://docs.scipy.org/doc/numpy-1.15.0/reference/constants.html), you can take $\pi$ from there. 

In [5]:
def sin_basic():
    return np.sin(np.arange(0,6.2,0.1))
    

In [6]:
PROBLEM_ID = 1

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, sin_basic)

### 2. Create a function, which calculates $n$ values of $\sin(x)$ for $0\leq x \leq 2\pi$.

Both $0$ and $2\pi$ must be included and $x$ values must be equidistant. Result must be **1-dimensional**, and **will be tested against three random values for $10 \leq n < 100 $**.

Example values to be calculated for $n=3$ are:

$$\sin(0),\sin(\pi),\sin(2\pi),$$

while for $n=5$ we have

$$\sin(0),\sin(\pi/2),\sin(\pi),\sin(3\pi/2), \sin(2\pi)$$.


In [7]:
def sin_enumerated(n):
    return  np.sin(np.linspace(0, 2*np.pi, n))


In [8]:
PROBLEM_ID = 2

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, sin_enumerated)

### 3. Create a function, which calculates $n$ values of truncated $\sin(x)$ for $0\leq x \leq 2\pi$.

Truncated $\sin(x)$ is defined as the following:

$$
\sin_{trunc}(x) =
\left\{
\begin{array}{l}
\sin(x), \sin(x)\geq 0, \\
0, \sin(x) < 0.
\end{array}\right.
$$

Otherwise, the requirements are the same as in Problem 2.

In [9]:
n = 7
np.linspace(0, 2*np.pi, n), np.sin(np.linspace(0, 2*np.pi, n))

(array([0.        , 1.04719755, 2.0943951 , 3.14159265, 4.1887902 ,
        5.23598776, 6.28318531]),
 array([ 0.00000000e+00,  8.66025404e-01,  8.66025404e-01,  1.22464680e-16,
        -8.66025404e-01, -8.66025404e-01, -2.44929360e-16]))

In [10]:
def sin_truncated(n):
    arr = np.sin(np.linspace(0, 2*np.pi, n))
    # for every value bigger than sin(1) => the output is smaller than 0
    if n == 1:
        return arr
    else:
        slice_point = np.ceil(n/2).astype('int')
        arr[slice_point:] = 0
    return arr 

sin_truncated(5)   

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16, 0.0000000e+00,
       0.0000000e+00])

In [11]:
PROBLEM_ID = 3

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, sin_truncated)

### 4. Statistics on multi-dimensional arrays.

Given a 3-dimensional array `arr`, calculate mean and standard deviation along dimensions $(1,2)$.

For a $N\times M \times K$ array `arr`, result must be a **2-dimensional** array of shape $N\times 2$, with column `0` containing mean values and column `1` containing standard deviations. For example, $(0,0)$ element of the resulting array contains mean of `arr[0]`, while $(1,1)$ contains standard deviation of `arr[1]`.

Your solution **will be tested against three random combinations of input array dimensions ($10 \leq n < 100 $)**. Array values will be drawn from the standard normal distribution (`np.random.randn`).

**Hint:** this problem may need to use some universal functions and array combination routines.

In [12]:
def array_stats(arr):
    return np.array([np.mean(arr, axis=(1,2)), np.std(arr, axis=(1,2))]).T
    

In [13]:
PROBLEM_ID = 4

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, array_stats)

### 5. Class prediction.

Given a probability matrix, you need to calculate the exact class, i.e. determine, which probability is the highest for each example. For example, for the following array

$$
\left(
\begin{array}{ccc}
0.3 && 0.6 && 0.1 \\
0.8 && 0.05 && 0.15
\end{array}
\right)
$$

the result must be

$$
\left(
\begin{array}{c}
1 \\
0
\end{array}
\right)
$$

Each row represents an example, and each column represent a probability for corresponding class. For example, element `(0, 1)` represents the probability of example `0` being of class `1`.

Note, that result must be **2-dimensional**, such that input array of shape $(N, M)$ is transformed into output array of shape $(N,1)$. Result **will be tested against three random combinations of input array dimensions ($10 \leq n < 100 $)**. Input array elements are drawn from the standard normal distribution with $\texttt{softmax}$ applied on top.

#### $\texttt{softmax}$

$\texttt{softmax}$ is used to represent **probabilities** and is often used as an activation function in neural networks for multi-class classification.

$\texttt{softmax}$ activation for a vector is defined as the following:

$$
\texttt{softmax} (x_i) = \frac{e^{x_i}}{\sum_i e^{x_i}}.
$$

Correspondingly, a `2D` array is transformed as the following:

$$
\texttt{softmax} (x_{ij}) = \frac{e^{x_{ij}}}{\sum_j e^{x_{ij}}}.
$$



For example, an input array 

$$
\left(
\begin{array}{cc}
1 && 6 \\
4 && 5
\end{array}
\right)
$$

results in the following $\texttt{softmax}$ activation:

$$
\left(
\begin{array}{cc}
\frac{e^1}{e^1 + e^6} && \frac{e^6}{e^1 + e^6} \\
\frac{e^4}{e^4 + e^5} && \frac{e^5}{e^4 + e^5}
\end{array}
\right)
$$


Result may be treated as **probabilistic predictions** of some classification model, as values sum to `1` for each row.

In [14]:
arr = np.array([[1,6],[4,5]])

In [15]:
def predict(arr):
  ## not sure arr is a numpy array, so turning it to numpy just in case
  arr = np.array(arr)
  e_power = np.e**arr
  prob_matrix = e_power / np.sum(e_power,axis=1, keepdims=True)

  return np.argmax(prob_matrix, axis=1)


In [16]:
predict(arr)

array([1, 1], dtype=int64)

In [54]:
PROBLEM_ID = 5

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, predict)

# Intermediate arrays

### 6. One-hot encoding.

Given 1-dimensional array of class labels, construct it's one-hot encoded transformation. One-hot encoding of an array of shape $(N,)$ is defined as an array of shape $(N,L)$, such that $e_{ij}$ is $1$ if $i$-th example belongs to class $j$ and $0$ otherwise. $L$ is the number of classes.

For example, array $(1,0,3,1,1,1,0)$ is transformed to

$$
\left(
\begin{array}{cccc}
0 && 1 && 0 && 0\\
1 && 0 && 0 && 0\\
0 && 0 && 0 && 1\\
0 && 1 && 0 && 0\\
0 && 1 && 0 && 0\\
0 && 1 && 0 && 0\\
1 && 0 && 0 && 0
\end{array}
\right)
$$

Class labels are consequtive integers, hence $L$ corresponds to the largest integer value in the input array. Note, that in the example above we do not have `2` in the input although the result is still $7\times 4$ with column `2` containing all `0`'s.

This function will be tested against three input arrays of random shape $(n,)$ ($10 \leq n < 100 $) filled with random integers.

**Hint:** you may need some fancy indexing.

In [55]:
np.zeros((5,np.max([0,1,2])))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
def onehot(labels):
    zeros = np.zeros((len(labels),np.max(labels)+1))
    zeros[np.arange(len(labels)),labels] = 1
    return zeros

In [57]:
PROBLEM_ID = 6

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, onehot)

### 7. Fixing missing values.

Given an array, which contains some $NaN$s (not-a-number, represented as `np.nan`), positive and negative infinities (represented as `np.inf`), contruct a "repaired" version of that array. All missing or broken values must be replaced by average of valid elements of an array.

For example, array $(0., np.nan, 2., np.inf)$ must be transformed to $(0., 1., 2., 1.)$.

Input arrays will be drawn from standard normal distribution, with small fraction of values transformed to either `np.nan`, `np.inf` or `-np.inf`.

**Hint:** you will need some masking to achieve the goal, as well as `np.isnan` and `np.isinf`.

In [58]:
def fix(arr):
    new_arr = np.array(arr)
    arr_mean = new_arr[np.isfinite(new_arr)].mean()
    new_arr[~np.isfinite(new_arr)] = arr_mean
    return new_arr

In [59]:
PROBLEM_ID = 7

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, fix)

### 8. Calculate class distribution.

Given 1-dimensional array of class labels, calculate occurrence of each class.

For example, array $(1,0,3,1,1,1,0)$ is transformed to $(2/7, 4/7, 0, 1/7)$. Class labels are consequtive integers, in the same way as in Problem 7 (note, that class `2` is not present in the input array, but it's occurence, although `0`, is included in the output).

Note the ordering and consider using one-hot representation to calculate class counts.

In [60]:
def class_freq(labels):
    ohe = onehot(labels)
    return np.sum(ohe, axis=(0))/len(labels)

In [61]:
class_freq((1,0,3,1,1,1,0))

array([0.28571429, 0.57142857, 0.        , 0.14285714])

In [ ]:
PROBLEM_ID = 8

if TEST:
    total_grade += solutions.check(STUDENT, PROBLEM_ID, class_freq)

# Your grade

In [ ]:
if TEST:
    print(f"{STUDENT}: {int(100 * total_grade / MAX_POINTS)}")