# Decision Trees Exercise
In this exercise you will show that ID3 is sub-optimal. Implement a simple version of Decision Tree, and will then apply a Decision Tree classsifier on the MNIST hand written digits dataset that we already saw.


## 1. Suboptimality of ID3
Consider the following training set, where $\mathcal{X} = \{0, 1\}^3$ and $\mathcal{Y} =\{0, 1\}$:

$$
\begin{aligned}
((1, 1, 1), 1)\\
((1, 0, 0), 1)\\
((1, 1, 0), 0)\\
((0, 0, 1), 0)
\end{aligned}
$$

Suppose we wish to use this training set in order to build a decision tree of depth 2 (i.e. for each
input we are allowed to ask two questions of the form "$x_i = 0$?" before deciding on the label).

1. Suppose we run the ID3 algorithm up to depth 2 (namely, we pick the root node and its
children according to the algorithm, but instead of keeping on with the recursion, we stop
and pick leaves according to the majority label in each subtree, once we reach depth 2). 
Assume that the subroutine used to measure the quality of each feature is based on the information gain, and that if two features get the same score, one of them is picked arbitrarily. 
Show that the training error of the resulting decision tree is at least 1/4.
2. Find a decision tree of depth 2, which attains zero training error.


#### Answer
![alt text](https://snipboard.io/DSFTtz.jpg)

#### Answer
![alt text](https://snipboard.io/DSFTtz.jpg)

## 2. Implementing Decision Tree From Scratch
In this exercise you will need to implement a simple version of Decision Tree from scratch. Your decision tree will handle **continuous input and output** (this should actually work also for binary input attributes).

* Compelete the skeleton class below
  - `X` is a matrix of data values (rows are samples, columns are attributes)
  - `y` is a vector of corresponding target values
  - `min_leaf` is the minimal number of samples in each leaf node
  
* For splitting criterion, use either **"Train Squared Error Minimization (Reduction in Variance)"** or **"Train Absolute Error Minimization"** (choose one). Whatever you choose, make sure you implement the splitting point decision efficiently (in $O(nlgn)$ time).

* The `predict` function will use mean of the target values in the leaf node matching each row of the given `X`. The result is a vector of predictions matching the number of rows in `X`.

* To check your decision tree implementation, use the boston dataset (`from sklearn.datasets import load_boston`) split the data set into train and test using (`from sklearn.model_selection import train_test_split`)

  - Use the following to estimate what are the best hyper parameters to use for your model
```
    for min_leaf in [1,5,10,100]:
      dt = DecisionTree(X, y, n, sz, min_leaf)
      mse = # mean square error over test set
      print("min_leaf:{0} --- oob mse: {1}".format(min_leaf, mse))
```
  
  - Using your chosen hyperparameters as a final model, plot the predictions vs. true values of all the samples in the training set . Use something like:
  ```
  y_hat = dt.predict(X_train)  # forest is the chosen model
  plt.scatter(y_hat, y_test)
  ```

In [54]:
# Libraries
import pandas as pd
from sklearn.datasets import load_boston
import numpy as np
import matplotlib.pyplot as plt

# Load the Boston dataset
boston_dataset = load_boston()


# Convert the dataset into a pandas dataframe
boston_df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
boston_df['target'] = boston_dataset.target
boston_df

c:\Users\itay8\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [12]:
arr = []
arr_2 = [1,2,3,4]
arr_3 = [5,6,7,8]
arr.append(arr_2)
arr.append(arr_3)

obj = {'left':arr_2, 'right':arr_3, 'feature_name':'aa', 'split_val':4}
if obj['split_val'] > 4:
    print(obj['right'])
else:
    print(obj['left'])

[1, 2, 3, 4]


In [69]:
import numpy as np
from sklearn.metrics import mean_squared_error

arr = np.array([5, 1, 2, 3, 4, ])
arr_2 = np.array([5, 4, 1, 2, 3 ])
y = np.array([ 10.3, 1, 10, 10.1, 10.2, ])

# get the average value between each two consecutive elements
avg_arr = (arr[:-1] + arr[1:])/2

print(avg_arr)


[3.  1.5 2.5 3.5]


In [70]:
# arr2_sorted_idx = np.argsort(arr_2)
# y_left, y_right = np.split(y[arr2_sorted_idx], [4])
# calc_rmse(y_left, y_left.mean()) + calc_rmse(y_right, y_right.mean()) 


In [71]:
print(arr)
idx_sorted = np.argsort(arr)
new_arr = arr[idx_sorted]


[5 1 2 3 4]


In [72]:
y_left, y_right = np.split(y, [2])
y_left, y_right

(array([10.3,  1. ]), array([10. , 10.1, 10.2]))

In [73]:
def calc_rmse(y_vals, y_mean):
    return np.sqrt((y_vals - y_mean)**2).mean()

In [75]:
def find_best_rmse(x, y):
    'Returns the split value and the rmse score'
    sorted_idx = np.argsort(x)
    sorted_x = x[sorted_idx]
    # avg_arr = (sorted_x[:-1] + sorted_x[1:])/2
    rmse_score = np.Inf
    split_val_idx = 0
    y_view = y[sorted_idx]
    for i in range(len(sorted_x)-1 ):

        y_left, y_right = np.split(y_view, [i+1])
        y_left_mean = np.mean(y_left)
        y_right_mean = np.mean(y_right)
        right_ratio = (y_right.shape[0]/y.shape[0])
        left_ratio = (y_left.shape[0]/y.shape[0])

        rmse = calc_rmse(y_left, y_left_mean)*left_ratio + calc_rmse(y_right, y_right_mean)*right_ratio
        if rmse < rmse_score:
            rmse_score = rmse
            split_val = (sorted_x[i] + sorted_x[i+1])/2
    return rmse_score, split_val

find_best_rmse(arr, y)

(0.08000000000000007, 1.5)

In [61]:
X = np.array([[5,,3,4,],[1,6,7,8], [2,10,11,12], [3,10,11,12], [4,10,11,12]])
y = np.array([10.3, 1, 10, 10.1, 10.2])
X

array([[ 5,  2,  3,  4],
       [ 1,  6,  7,  8],
       [ 2, 10, 11, 12],
       [ 3, 10, 11, 12],
       [ 4, 10, 11, 12]])

In [ ]:
def fit(df, y):
    best_rmse = np.Inf
    best_split_val = None
    best_feature = None
    
    for col in df.columns:
        rmse_score, split_val = find_best_rmse[df[col], y]
        if best_rmse > rmse_score:
            best_rmse = rmse_score
            best_split_val = split_val
            best_feature = col

    print(best_rmse, best_split_val, best_feature)
            
    
    
    

In [17]:
class DecisionTree():
  def __init__(self, X, y, min_leaf):
    self.X = X
    self.y = y
    self.min_leaf = min_leaf

  # fit:
  # we receive data
  # Sort the features by values
  # Calculate RMSE for each feature for different values in that feature
  # Values are decided by iterating over paris of values
  # Save the best RMSE for that feature in array
  # Sort the array, creating nodes is determined by the order of the array?
  # Create Root node
  # split the samples accordingly to each node
  # calculate the RMSE in that node for the selected samples in it, for each feature 
  def calc_rmse(y_vals, y_mean):
    return np.sqrt((y_vals - y_mean)**2).mean()

  def find_best_rmse(x, y):
    'Returns the split value and the rmse score'
    sorted_idx = np.argsort(x)
    sorted_x = x[sorted_idx]
    # avg_arr = (sorted_x[:-1] + sorted_x[1:])/2
    rmse_score = np.Inf
    split_val_idx = 0
    y_view = y[sorted_idx]
    for i in range(len(sorted_x)-1 ):

        y_left, y_right = np.split(y_view, [i+1])
        y_left_mean = np.mean(y_left)
        y_right_mean = np.mean(y_right)
        rmse = calc_rmse(y_left, y_left_mean) + calc_rmse(y_right, y_right_mean)
        if rmse < rmse_score:
            rmse_score = rmse
            split_val = (sorted_x[i] + sorted_x[i+1])/2
    return rmse_score, split_val


    # need
  def fit(self):
    
    pass

  def predict(self, X):
    pass



## 3. Using Decision Tree for Digits Classification
Remeber the MNIST dataset used - you will now test the power of decision trees on this problem.
This time you are given a free hand in choosing the test and train set sizes, model parameters (such as gain function and constraints over the trees) and features (whether to use binary pixel values or the original continous gray value).
  - You can use `sklearn.tree.DecisionTreeClassifier`
- Once you are satisfied with the model parameters, plot the importance of each of the pixels to the final decision.
- Last, estimate the class assignment probabilities for all the correctly classified and misclassified examples in your test data.
- Discuss your results.

In [ ]:
# code and answer go here